flyway:
  enabled: true
  locations: classpath:db/migration
  schemas: [ hypnobook ]

spring:
  datasource:
    url: jdbc:postgresql://10.12.0.1:5435/hypnobook
    password: appuser
    username: appuser